version: "3.8"
services:
  db:
    image: mysql:8.0.36
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ant
    ports:
      - "3306:3306"
  traefik:
    image: traefik:v3.2
    command: 
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8888"
      - "--entrypoints.traefik.address=:9876"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entryPoints=traefik"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
    ports:
      - "8888:8888"
      - "9876:9876"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  client:
    build:
      context: ./Ant-client
      dockerfile: ../Dockerfile.client
    environment:
      - PORT=3434
      - NODE_ENV=development
      - VITE_API_ENDPOINT=http://localhost:8080
      - VITE_GOOGLE_CLIENT_ID=YOUR_GOOGLE_CLIENT_ID
      - VITE_GOOGLE_REDIRECT_URI=http://localhost:3434
      - VITE_GOOGLE_SCOPE=profile email
    volumes:
      - ./Ant-client/src:/Ant-client/src
      - ./Ant-client/vite.config.ts:/Ant-client/vite.config.ts
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`ant.localhost`)"
      - "traefik.http.services.client.loadbalancer.server.port=3434"
    depends_on:
      - traefik
      - server
    # scaleout
    # deploy:
    #   mode: replicated
    #   replicas: 3
  server:
    build:
      context: ./Ant-server
      dockerfile: ../Dockerfile.server
    environment:
      - CORS_ORIGIN=http://ant.localhost:3434
      - TZ=UTC
      - PORT=8080
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    volumes:
      - ./Ant-server/src/:/Ant-server/src/
      